# Generated by Django 3.1.5 on 2021-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0003_loanrequest_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
