# Generated by Django 3.1.5 on 2021-09-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0004_auto_20210903_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loancategory'),
        ),
    ]
