# Generated by Django 3.1.5 on 2021-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0005_loanrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='reason',
            field=models.TextField(),
        ),
    ]
