# Generated by Django 3.1.5 on 2021-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0007_auto_20210904_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status_date',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
