# Generated by Django 3.1.5 on 2021-09-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='Dhaka,Bangladesh', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customersignup',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersignup',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
